### ISSUE TITLE
error in hotword.py when launching googlesamples-assistant-hotword

### ISSUE THREAD

**Issue by janvda** [janvda/balena-google-assistant#1]
log
```
(env) root@f0bc010:/# googlesamples-assistant-hotword --project-id pi3three-balena --device-model-id pi3three-balena-pi3three-balena-x3hx44 --credentials /credentials.json
Traceback (most recent call last):
  File "/env/bin/googlesamples-assistant-hotword", line 10, in <module>
    sys.exit(main())
  File "/env/lib/python3.5/site-packages/googlesamples/assistant/library/hotword.py", line 106, in main
    **json.load(f))
TypeError: __init__() got an unexpected keyword argument 'installed'
(env) root@f0bc010:/# 
```

**Comment by janvda** [comment]
workaround proposal: in stead of passing as argument - put the file in the default location.

**Comment by janvda** [comment]
Is fixed by the solution proposed by https://stackoverflow.com/a/49395491/6762442
or in other words I had the follow the instructions of section "Generate the Credentials" specified on page : https://developers.google.com/assistant/sdk/guides/library/python/embed/install-sample
